- .cargo/config
- .github/workflows/docker-build.yml
- src/common.rs
- utils/alpine-linker-script.sh
- utils/docker/Dockerfile
- utils/docker/build-docker.sh
- utils/docker/entrypoint.sh
> feat: build Docker image in CI

- .github/workflows/release-please.yml
- .github/workflows/rust.yml
- (hopefully) properly publish Docker images with versions on ghcr.io
- (hopefully) properly cache librocksdb-sys with rust-cache
Release-As: 0.5.6
> build: some small fixes to CI

- Cargo.lock
- Cargo.toml
- src/annotate/seqvars/csq.rs
- src/annotate/seqvars/mod.rs
- src/annotate/seqvars/provider.rs
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41196309-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41196310-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41196311-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41196312-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41196313-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41197701-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41197818-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41197819-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41197820-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41197821-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41197822-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41197823-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41277379-A-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41277380-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41277381-G-T.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41277382-G-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41277383-A-C.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_brca1_one_variant@17-41277384-G-C.snap
- src/annotate/strucvars/csq.rs
- src/annotate/strucvars/mod.rs
- src/common.rs
- src/verify/seqvars.rs
- tests/data/annotate/db/grch37/bootstrap.sh
- tests/data/annotate/db/grch37/txs.bin.zst
- tests/data/annotate/db/grch37/txs.bin.zst.report
> fix: index out of bounds error in stop_retained variant (#226)

- src/annotate/seqvars/mod.rs
- src/annotate/strucvars/mod.rs
- src/common/io/std.rs
> fix: properly flush and sync all writers

- src/main.rs
- src/server/actix_server/mod.rs
- src/server/mod.rs
> fix: remove second async runtime creation

- Cargo.lock
- misc/fix_freebayes.py
- misc/fix_freebayes.requirements.txt
> feat: adding helper script to fix FreeBayes VCF (#252)

- src/annotate/seqvars/mod.rs
> fix!: make --path-input-ped for seqvars annotation required (#194)

- misc/convert_clincnv.py
- misc/convert_clincnv.requirements.txt
- misc/fix_freebayes.py
- src/annotate/seqvars/mod.rs
- src/annotate/strucvars/mod.rs
- src/annotate/strucvars/snapshots/mehari__annotate__strucvars__test__guess_sv_caller_clincnv.snap
- tests/data/annotate/strucvars/clincnv-min.out.jsonl
- tests/data/annotate/strucvars/clincnv-min.vcf
Note that the TSV files must be converted to VCF first using the helper script in misc/convert_clincnv.py.
> feat: adding support for ClinCNV (#253)

- src/annotate/seqvars/provider.rs
> fix: fixing implementation of Provider::get_tx_for_gene

- utils/docker/Dockerfile
- utils/docker/build-docker.sh
> fix: copy in protobufs into docker builds

- Cargo.lock
- Cargo.toml
- build.rs
- protos/mehari/txs.proto
- src/annotate/seqvars/csq.rs
- src/annotate/seqvars/mod.rs
- src/annotate/seqvars/provider.rs
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_ttn_transcript_picking_reporting@2-179631246-G-A-false-true.snap
- src/annotate/seqvars/snapshots/mehari__annotate__seqvars__csq__test__annotate_snv_ttn_transcript_picking_reporting@2-179631246-G-A-true-true.snap
- src/db/create/mod.rs
- src/db/create/snapshots/mehari__db__create__test__run_smoke_brca1_opa1.snap
- src/db/create/snapshots/mehari__db__create__test__run_smoke_selenoproteins.snap
- tests/data/annotate/db/grch37/bootstrap.sh
- tests/data/annotate/db/grch37/txs.bin.zst
- tests/data/annotate/db/grch37/txs.bin.zst.report
- tests/data/annotate/vars/bootstrap.sh
- tests/data/db/create/txs/bootstrap.sh
This adds a dummy "_UNKNOWN = 0;" value to all enums for compatility with pb-json package.
Release-As: 0.21.0
> fix!: adjusting enum values

- Cargo.lock
- Cargo.toml
> fix: bumping annonars dependency to fix protobuf issues

- CHANGELOG.md
- Cargo.toml
- README.md
- docs/db_build.md
- docs/getting_started.md
- docs/index.md
- utils/docker/build-docker.sh
> chore: applying org change (bihealth => varfish-org)

- .github/workflows/add-issue-to-project.yml
- .github/workflows/add-pr-to-project.yml
This reverts commit a7ffa9de8e9be26bac59eef637b9434ff3dd4c4b.
> Revert "ci: removing "add to project GitHub actions" (#355)"

- Cargo.toml
> chore: using repository field in Cargo.toml

- Cargo.lock
- Cargo.toml
> fix: bump annonars dependency

- src/annotate/mod.rs
- src/annotate/seqvars/mod.rs
- src/annotate/strucvars/mod.rs
- src/common/mod.rs
- src/common/noodles.rs
> fix: make previously public code public again

- .github/dependabot.yml
> build: ignore rocksdb and noodles deps

- Cargo.toml
- src/annotate/strucvars/mod.rs
> fix: make cargo release work again

- utils/docker/Dockerfile
- utils/install-protoc.sh
> ci: install binary protoc in utils/install-protoc.sh

- src/annotate/seqvars/mod.rs
> fix: make seqvar annotators public for varfish-server-worker

- .github/workflows/release-please.yml
- .github/workflows/rust.yml
> fix: install libsnappy-dev in CI

- .github/workflows/automerge.yml
- .github/workflows/conventional-prs.yml
- .github/workflows/docker-build.yml
- .github/workflows/release-please.yml
- .github/workflows/rust.yml
> ci: bump ubuntu to 24.04

- .github/workflows/release-please.yml
- .github/workflows/rust.yml
> ci: adding dependency libsqlite3-dev

- .github/workflows/rust.yml
> chore: run cargo test in ci

- Cargo.lock
- src/annotate/seqvars/csq.rs
- src/annotate/seqvars/mod.rs
- src/annotate/strucvars/maelstrom.rs
- src/annotate/strucvars/mod.rs
- src/common/io/std.rs
- src/common/mod.rs
- src/db/subset/mod.rs
- src/server/run/mod.rs
- src/verify/seqvars.rs
Migrate project to rust edition 2024
> chore: migrate to edition 2024
